__title__ = 'mindsdb_server'
__package_name__ = 'mindsdb_server'
__version__ = '1.6.0'
__description__ = "MindsDB server, provides server capabilities to mindsdb native python library"
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb_server'
__pypi__ = 'https://pypi.org/project/mindsdb-server/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018- mindsdb'
